from django.contrib import admin

# Register your models here.


from .models import User,Whitelisted, RECENTLYJOINED, ANGELS,CAPTURECARDS, FL, TRANSFERSDEPOSIT, WITHDRAWALDEPOSIT, WINNERS, ORDERS, SERVERSBN,globseason,CAPTUREADMIN,glitch,ProvablyFair, Seasontime,Roundtime, Numbers, Playing,SERVERSIDE, DataOBJ,DELETEDUSERS, Support,Modifiers, black, Money, PlayingMode, Keys, Leaderboard, UsedKeys,Ticket, Level, Market, Trade, Chat,Messages,Slot,Inventory,Luck,TradeSpace,LuckCalc,SERVERS



admin.site.register(glitch)
admin.site.register(CAPTURECARDS)
admin.site.register(Playing)
admin.site.register(Modifiers)
admin.site.register(black)
admin.site.register(Money)
admin.site.register(PlayingMode)
admin.site.register(Ticket)
admin.site.register(Market)
admin.site.register(Level)
admin.site.register(Trade)
admin.site.register(Chat)
admin.site.register(Messages)
admin.site.register(Inventory)
admin.site.register(Slot)
admin.site.register(Luck)
admin.site.register(TradeSpace)
admin.site.register(LuckCalc)
admin.site.register(User)
admin.site.register(Keys)
admin.site.register(UsedKeys)
admin.site.register(Leaderboard)
admin.site.register(Support)
admin.site.register(DELETEDUSERS)
admin.site.register(SERVERSIDE)
admin.site.register(SERVERS)
admin.site.register(Seasontime)
admin.site.register(Roundtime)
admin.site.register(ProvablyFair)
admin.site.register(Numbers)
admin.site.register(globseason)
admin.site.register(SERVERSBN)
admin.site.register(WINNERS)
admin.site.register(CAPTUREADMIN)
admin.site.register(Whitelisted)
admin.site.register(ORDERS)
admin.site.register(WITHDRAWALDEPOSIT)
admin.site.register(TRANSFERSDEPOSIT)
admin.site.register(ANGELS)
admin.site.register(FL)
admin.site.register(RECENTLYJOINED)