# Generated by Django 4.2.7 on 2024-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='minleveldata',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='roundtype',
            field=models.CharField(default='Normal', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='seasontype',
            field=models.CharField(default='Normal', max_length=256),
            preserve_default=False,
        ),
    ]
