# Generated by Django 4.2.7 on 2024-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_game_minleveldata_game_roundtype_game_seasontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_amount', models.FloatField()),
                ('keyseed', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UsedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_amount', models.FloatField()),
                ('keyseed', models.CharField(max_length=256)),
                ('p_used', models.CharField(max_length=256)),
            ],
        ),
    ]
