# Generated by Django 4.2.7 on 2024-01-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_keys_usedkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='p_luck',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
