# Generated by Django 4.2.7 on 2024-01-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_ticket_p_luck'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='optimization',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
