# Generated by Django 4.2.7 on 2024-01-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_money_f_luck'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiers',
            name='chumps',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money',
            name='f_luck',
            field=models.FloatField(),
        ),
    ]
