# Generated by Django 4.2.7 on 2024-01-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='P_tmoney',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_acceptfriends',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_currentrade',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='p_exp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_forceluck',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_luck',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_messagesaccept',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_money',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_orders',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_playing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_storedluck',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_trades',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
