# Generated by Django 4.2.7 on 2024-01-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_user_p_tmoney_user_p_acceptfriends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FAKEY',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
