# Generated by Django 4.2.7 on 2024-01-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_user_fakey_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='Adminrep',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
