# Generated by Django 4.2.7 on 2024-01-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_support_adminrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=16)),
                ('friend', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=16)),
                ('friend', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.CharField(max_length=256)),
                ('ProfilePicture', models.CharField(max_length=256)),
                ('AgeRestriction', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='FAKEY',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='P_tmoney',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_acceptfriends',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_currentrade',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_exp',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_forceluck',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_level',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_luck',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_messagesaccept',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_money',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_orders',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_playing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_storedluck',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_trades',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
