# Generated by Django 4.2.7 on 2024-01-18 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_ticket_p_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.PositiveIntegerField(default=999, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='PFP',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
