# Generated by Django 4.2.7 on 2024-01-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_user_age_user_bio_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BanRs',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Banned',
            field=models.BooleanField(default=False),
        ),
    ]
