# Generated by Django 4.2.7 on 2024-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_user_banrs_user_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BanRs',
        ),
        migrations.AddField(
            model_name='user',
            name='BanRes',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
