# Generated by Django 4.2.7 on 2024-01-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_remove_user_banrs_user_banres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='black',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
