# Generated by Django 4.2.7 on 2024-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_alter_black_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dailylimit',
            field=models.PositiveIntegerField(default=100000000000),
        ),
        migrations.AddField(
            model_name='user',
            name='moneyspent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='moneywon',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totaldaily',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
