# Generated by Django 4.2.7 on 2024-01-21 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_user_dailylimit_user_moneyspent_user_moneywon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
