# Generated by Django 4.2.7 on 2024-01-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_ticket_datetime_ticket_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
