# Generated by Django 4.2.7 on 2024-01-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Requests',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
