# Generated by Django 4.2.7 on 2024-01-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_user_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AcceptReq',
            field=models.BooleanField(default=True),
        ),
    ]
