# Generated by Django 4.2.7 on 2024-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_remove_messages_keymsg_remove_messages_p_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MOD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='p_content',
            field=models.CharField(max_length=128),
        ),
    ]
