# Generated by Django 4.2.7 on 2024-01-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0028_user_mod_alter_chat_p_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='p_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedkeys',
            name='p_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usedkeys',
            name='p_used',
            field=models.CharField(max_length=16),
        ),
    ]
