# Generated by Django 4.2.7 on 2024-01-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0030_keysbanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='keysbanned',
            name='p_used',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
