# Generated by Django 4.2.7 on 2024-01-29 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0031_keysbanned_p_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='DELETEDUSERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('p_money', models.FloatField(default=0)),
                ('p_storedluck', models.FloatField(default=0)),
                ('p_luck', models.FloatField(default=1)),
                ('p_level', models.PositiveIntegerField(default=0)),
                ('p_orders', models.PositiveIntegerField(default=0)),
                ('p_exp', models.PositiveIntegerField(default=0)),
                ('p_trades', models.BooleanField(default=True)),
                ('P_tmoney', models.BooleanField(default=False)),
                ('p_playing', models.BooleanField(default=False)),
                ('FAKEY', models.CharField(default='', max_length=16)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('Bio', models.CharField(max_length=256)),
                ('moneywon', models.PositiveIntegerField(default=0)),
                ('moneyspent', models.PositiveIntegerField(default=0)),
                ('Friends', models.CharField(max_length=100000)),
                ('Requests', models.CharField(max_length=100000)),
            ],
        ),
    ]
