# Generated by Django 4.2.7 on 2024-02-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0032_deletedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='datetime',
        ),
    ]
