# Generated by Django 4.2.7 on 2024-02-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0034_ticket_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='PAUSE',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ROUNDSTARTING',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='TOOKORDERS',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
