# Generated by Django 4.2.7 on 2024-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0035_game_pause_game_roundstarting_game_tookorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing',
            name='p_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
