# Generated by Django 4.2.7 on 2024-02-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0036_playing_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVERSIDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance', models.BooleanField(default=False)),
            ],
        ),
    ]
