# Generated by Django 4.2.7 on 2024-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0037_serverside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='minleveldata',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='roundcounter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='seasonseed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='seasontime',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='seshcount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
