# Generated by Django 4.2.7 on 2024-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0039_serverside_playeramount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverside',
            name='PLAYERAMOUNT',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
