# Generated by Django 4.2.7 on 2024-02-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0040_alter_serverside_playeramount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='roundseed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='roundtime',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playingmode',
            name='s_playing',
            field=models.BooleanField(default=True),
        ),
    ]
