# Generated by Django 4.2.7 on 2024-02-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0041_alter_game_roundseed_alter_game_roundtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='seasontype',
        ),
    ]
