# Generated by Django 4.2.7 on 2024-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0042_remove_game_seasontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seasontype',
            field=models.CharField(default='normal', max_length=256),
            preserve_default=False,
        ),
    ]
