# Generated by Django 4.2.7 on 2024-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0043_game_seasontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverside',
            name='BETA',
            field=models.BooleanField(default=True),
        ),
    ]
