# Generated by Django 4.2.7 on 2024-03-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0044_serverside_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverside',
            name='R_TIMER',
            field=models.PositiveIntegerField(default=2240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='Msgcontent',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='dailylimit',
            field=models.PositiveIntegerField(default=10000000),
        ),
    ]
