# Generated by Django 4.2.7 on 2024-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0045_serverside_r_timer_alter_messages_msgcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiers',
            name='soresplit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modifiers',
            name='winnersplit',
            field=models.FloatField(),
        ),
    ]
