# Generated by Django 4.2.7 on 2024-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0046_alter_modifiers_soresplit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=64)),
                ('sores', models.FloatField(default=0.0072)),
                ('chumps', models.FloatField(default=0.0072)),
                ('description', models.CharField(max_length=256)),
                ('method', models.CharField(max_length=64)),
                ('timetomax', models.CharField(max_length=128)),
                ('difficulty', models.FloatField(default=1)),
                ('fl_difficulty', models.FloatField(default=1)),
                ('rtp', models.FloatField(default=99.9)),
                ('s_time', models.FloatField(default=10000)),
                ('o_luck', models.FloatField(default=0.2)),
                ('o_exp', models.FloatField(default=0.2)),
                ('ordercost', models.FloatField(default=1)),
                ('image', models.CharField(default='', max_length=256)),
                ('intime', models.FloatField()),
                ('randomskit', models.BooleanField(default=False)),
                ('soresgetmin', models.IntegerField(default=80)),
                ('maxchumpchangedisp', models.FloatField(default=0.1)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='moneyspent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='moneywon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_money',
            field=models.FloatField(default=2500),
        ),
        migrations.AlterField(
            model_name='user',
            name='totaldaily',
            field=models.FloatField(default=0),
        ),
    ]
