# Generated by Django 4.2.7 on 2024-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0047_servers_alter_user_moneyspent_alter_user_moneywon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='servertype',
            field=models.CharField(default='Official', max_length=32),
            preserve_default=False,
        ),
    ]
