# Generated by Django 4.2.7 on 2024-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0048_servers_servertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='s_name',
            field=models.CharField(max_length=64),
        ),
    ]
