# Generated by Django 4.2.7 on 2024-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0049_alter_servers_s_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing',
            name='p_server',
            field=models.CharField(default='Official: 1$ Orders - No Rules - No Limits', max_length=64),
        ),
    ]
