# Generated by Django 4.2.7 on 2024-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0051_servers_levelmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roundtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('roundtype', models.CharField(max_length=32)),
                ('s_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Seasontime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('s_name', models.CharField(max_length=32)),
                ('roundtype', models.CharField(max_length=32)),
                ('end', models.FloatField()),
            ],
        ),
    ]
