# Generated by Django 4.2.7 on 2024-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0053_rename_levelmin_servers_levelmax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RemoveField(
            model_name='seasontime',
            name='maxleveldata',
        ),
        migrations.AlterField(
            model_name='roundtime',
            name='s_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='seasontime',
            name='s_name',
            field=models.CharField(max_length=64),
        ),
    ]
