# Generated by Django 4.2.7 on 2024-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0054_delete_game_remove_seasontime_maxleveldata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtime',
            name='intermission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seasontime',
            name='intermission',
            field=models.FloatField(default=0),
        ),
    ]
