# Generated by Django 4.2.7 on 2024-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0056_seasontime_roundstarting'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtime',
            name='roundstarting',
            field=models.BooleanField(default=True),
        ),
    ]
