# Generated by Django 4.2.7 on 2024-05-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0057_roundtime_roundstarting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasontime',
            old_name='roundstarting',
            new_name='seasonstarting',
        ),
    ]
