# Generated by Django 4.2.7 on 2024-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0058_rename_roundstarting_seasontime_seasonstarting'),
    ]

    operations = [
        migrations.CreateModel(
            name='globseason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
            ],
        ),
    ]
