# Generated by Django 4.2.7 on 2024-05-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0059_globseason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasontime',
            old_name='roundtype',
            new_name='seasontype',
        ),
    ]
