# Generated by Django 4.2.7 on 2024-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0060_rename_roundtype_seasontime_seasontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='l_name',
            field=models.CharField(default='generator', max_length=32),
        ),
    ]
