# Generated by Django 4.2.7 on 2024-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0061_servers_l_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvablyFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=64)),
                ('scrambled', models.CharField(max_length=10000000)),
                ('unscrambled', models.CharField(max_length=10000000)),
                ('winningnumbers', models.CharField(max_length=10000)),
                ('losingnumbers', models.CharField(max_length=10000)),
            ],
        ),
    ]
