# Generated by Django 4.2.7 on 2024-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0062_provablyfair'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing',
            name='p_exp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
