# Generated by Django 4.2.7 on 2024-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0063_playing_p_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifiers',
            old_name='seasoncounter',
            new_name='seasoncount',
        ),
        migrations.RemoveField(
            model_name='modifiers',
            name='baseforceluck',
        ),
        migrations.RemoveField(
            model_name='modifiers',
            name='baseluck',
        ),
        migrations.RemoveField(
            model_name='modifiers',
            name='takemoney',
        ),
        migrations.AddField(
            model_name='modifiers',
            name='s_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
