# Generated by Django 4.2.7 on 2024-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0064_rename_seasoncounter_modifiers_seasoncount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=64)),
                ('number', models.FloatField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='provablyfair',
            name='losingnumbers',
        ),
        migrations.RemoveField(
            model_name='provablyfair',
            name='winningnumbers',
        ),
    ]
