# Generated by Django 4.2.7 on 2024-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0065_numbers_remove_provablyfair_losingnumbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='p_server',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
