# Generated by Django 4.2.7 on 2024-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0066_chat_p_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPTUREADMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENTHELP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('amount_before', models.FloatField()),
                ('amount_after', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SERVERSBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='money',
            name='f_luck',
        ),
        migrations.RemoveField(
            model_name='money',
            name='s_losers',
        ),
        migrations.RemoveField(
            model_name='money',
            name='s_sores_order',
        ),
        migrations.RemoveField(
            model_name='money',
            name='s_umg_order',
        ),
        migrations.RemoveField(
            model_name='money',
            name='s_winners',
        ),
        migrations.RemoveField(
            model_name='money',
            name='s_won_order',
        ),
    ]
