# Generated by Django 4.2.7 on 2024-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0069_whitelisted_serversbn_tobefl'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='stat',
            field=models.CharField(default='stat', max_length=16),
        ),
    ]
