# Generated by Django 4.2.7 on 2024-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0070_money_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversbn',
            name='tobesores',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serversbn',
            name='tobewinner',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
