# Generated by Django 4.2.7 on 2024-05-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0071_serversbn_tobesores_serversbn_tobewinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WINNERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('s_name', models.CharField(max_length=64)),
            ],
        ),
    ]
