# Generated by Django 4.2.7 on 2024-05-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0072_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
