# Generated by Django 4.2.7 on 2024-05-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0073_winners_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
