# Generated by Django 4.2.7 on 2024-05-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0074_winners_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='image',
            field=models.FloatField(default=0),
        ),
    ]
