# Generated by Django 4.2.7 on 2024-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0075_alter_servers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='provablyfair',
            name='l_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
