# Generated by Django 4.2.7 on 2024-05-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0076_provablyfair_l_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundtime',
            old_name='s_name',
            new_name='l_name',
        ),
    ]
