# Generated by Django 4.2.7 on 2024-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0077_rename_s_name_roundtime_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundtime',
            name='s_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
