# Generated by Django 4.2.7 on 2024-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0078_roundtime_s_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='round_end',
            field=models.FloatField(default=360),
        ),
        migrations.AddField(
            model_name='servers',
            name='round_start',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servers',
            name='season_end',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='servers',
            name='season_start',
            field=models.FloatField(default=0),
        ),
    ]
