# Generated by Django 4.2.7 on 2024-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0079_servers_round_end_servers_round_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='planet',
            field=models.CharField(default="Goku's house", max_length=64),
        ),
    ]
