# Generated by Django 4.2.7 on 2024-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0082_servers_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='p_money',
            field=models.FloatField(default=0),
        ),
    ]
