# Generated by Django 4.2.7 on 2024-05-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0083_alter_user_p_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='L_name',
            field=models.CharField(default='main', max_length=64),
        ),
    ]
