# Generated by Django 4.2.7 on 2024-05-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0085_servers_place_orders_servers_intermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='seasonstarting',
            field=models.BooleanField(default=True),
        ),
    ]
