# Generated by Django 4.2.7 on 2024-05-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0086_servers_seasonstarting'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='chumps_disp',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='servers',
            name='sores_disp',
            field=models.FloatField(default=1),
        ),
    ]
