# Generated by Django 4.2.7 on 2024-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0087_servers_chumps_disp_servers_sores_disp'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='server',
            field=models.CharField(default='main', max_length=64),
        ),
        migrations.AlterField(
            model_name='servers',
            name='chumps',
            field=models.FloatField(default=0.005),
        ),
    ]
