# Generated by Django 4.2.7 on 2024-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0088_level_server_alter_servers_chumps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winners',
            old_name='amount',
            new_name='p_amount',
        ),
        migrations.RenameField(
            model_name='winners',
            old_name='username',
            new_name='p_class',
        ),
        migrations.AddField(
            model_name='winners',
            name='p_level',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winners',
            name='p_luck',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winners',
            name='p_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
