# Generated by Django 4.2.7 on 2024-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0091_serversbn_roundtype_serversbn_seasontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='black',
            name='server',
            field=models.CharField(default='main', max_length=64),
        ),
    ]
