# Generated by Django 4.2.7 on 2024-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0092_black_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVERSPAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='server',
            field=models.CharField(default='main', max_length=64),
        ),
    ]
