# Generated by Django 4.2.7 on 2024-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0093_serverspam_ticket_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='season',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
