# Generated by Django 4.2.7 on 2024-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0094_servers_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='o_exp',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='servers',
            name='o_luck',
            field=models.FloatField(default=1),
        ),
    ]
