# Generated by Django 4.2.7 on 2024-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0095_alter_servers_o_exp_alter_servers_o_luck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiers',
            name='umgtax',
        ),
    ]
