# Generated by Django 4.2.7 on 2024-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0096_remove_modifiers_umgtax'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='rarity',
            field=models.CharField(default='', max_length=64),
        ),
    ]
