# Generated by Django 4.2.7 on 2024-05-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0097_winners_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('server', models.CharField(max_length=64)),
                ('player', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ORDERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('server', models.CharField(max_length=64)),
                ('player', models.CharField(max_length=16)),
            ],
        ),
    ]
