# Generated by Django 4.2.7 on 2024-05-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0099_black_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='intime',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='servers',
            name='players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servers',
            name='servertype',
            field=models.CharField(default='Unofficial', max_length=32),
        ),
        migrations.AlterField(
            model_name='servers',
            name='timetomax',
            field=models.PositiveIntegerField(default=360),
        ),
    ]
