# Generated by Django 4.2.7 on 2024-05-12 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0101_fl_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='levelmax',
            field=models.IntegerField(default=320, validators=[django.core.validators.MaxValueValidator(320), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='servers',
            name='maxchumpchangedisp',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='serversbn',
            name='fl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='serversbn',
            name='minlevelseedata',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serversbn',
            name='tobefl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='serversbn',
            name='tobesores',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='serversbn',
            name='tobewinner',
            field=models.FloatField(default=0),
        ),
    ]
