# Generated by Django 4.2.7 on 2024-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0103_alter_servers_max_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiers',
            name='seasoncount',
        ),
        migrations.AlterField(
            model_name='modifiers',
            name='chumps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modifiers',
            name='sores',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
