# Generated by Django 4.2.7 on 2024-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0104_remove_modifiers_seasoncount_alter_modifiers_chumps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='method',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
