# Generated by Django 4.2.7 on 2024-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0105_alter_servers_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversbn',
            name='incentive',
            field=models.FloatField(default=0),
        ),
    ]
