# Generated by Django 4.2.7 on 2024-05-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0107_transfersdeposit_withdrawaldeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaldeposit',
            name='groupuser',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
