# Generated by Django 4.2.7 on 2024-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0108_withdrawaldeposit_groupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANGELS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=16)),
                ('p_class', models.CharField(max_length=16)),
                ('p_luck', models.FloatField()),
                ('p_level', models.PositiveIntegerField()),
                ('s_name', models.CharField(max_length=64)),
                ('number', models.PositiveIntegerField()),
                ('p_amount', models.FloatField()),
                ('rarity', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
