# Generated by Django 4.2.7 on 2024-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0111_alter_servers_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='playing_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
