# Generated by Django 4.2.7 on 2024-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0112_ticket_playing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPTURECARDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('capture_id', models.CharField(max_length=32)),
                ('capture_image', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='CAPTURE_CARD',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_money',
            field=models.FloatField(default=50000),
        ),
    ]
