# Generated by Django 4.2.7 on 2024-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0113_capturecards_user_capture_card_alter_user_p_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CAPTURE_CARD',
            field=models.CharField(default='', max_length=128),
        ),
    ]
