# Generated by Django 4.2.7 on 2024-05-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0115_alter_capturecards_capture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capturecards',
            old_name='capture_image',
            new_name='image',
        ),
    ]
