# Generated by Django 4.2.7 on 2024-05-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0116_rename_capture_image_capturecards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturecards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
