# Generated by Django 4.2.7 on 2024-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0117_alter_capturecards_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RECENTLYJOINED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='CAPTURE_CARD',
            field=models.CharField(default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='p_money',
            field=models.FloatField(default=0),
        ),
    ]
